import type { Metadata } from "next"

import Footer from "@/components/Footer"
import { sans } from "@/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Frontend Mentor | Order Summary Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
