import type { Metadata } from "next"

import "./globals.css"
import { sans } from "@/fonts"
import Footer from "@/components/ui/Footer"
import Banner from "@/components/ui/Banner"

export const metadata: Metadata = {
  title: "Frontend Mentor | Order Summary Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} bg-primary-pale-blue bg-desktop-design flex min-h-screen flex-col items-center justify-center`}
      >
        <Banner />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
